server:
  address: 127.0.0.1
  port: 8081


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
#    druid:
#      # stat: 监控统计用的插件
#      filters: stat
#      # 最大连接池数量
#      max-active: 20
#      # 初始化时建立物理连接的个数
#      initial-size: 3
#      # 连接时最大等待时间
#      max-wait: 60000
#      # 最小连接池数量
#      min-idle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      # 连接保持空闲而不被驱逐的最小时间
#      minEvictableIdleTimeMillis: 300000
#      # 用来检测连接是否有效的sql，要求是一个查询语句
#      validationQuery: select 'x'
#      # 不影响性能,并且保证安全性
#      testWhileIdle: true
#      # 开启会影响性能
#      testOnBorrow: false
#      # 开启会影响性能
#      testOnReturn: false
#      # 是否缓存preparedStatement,PSCache对支持游标的数据库性能提升巨大,mysql下建议关闭
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
